readthedocs/addons

.pre-commit-config.yaml
public/index.html
src/search.js

Define two new attributes `show-modal-selector` and `show-modal-event` to allow the user defining which HTML element will show the modal.
In this example, when clicking on the `input` it will show the modal.

Search: define which element & event shows the modal

---

src/index.js
src/new-flyout.js
src/notification.js
src/search.js

We had a problem when enabling multiple addons because the manipulation of the DOM in an async way. This commit uses a different pattern that solves this issue.
Closes #91

Enable search + flyout and don't break

---

.pre-commit-config.yaml
.pre-commit-hooks.yaml
check-build-assets.sh

This is the continuation of the work done in https://github.com/readthedocs/addons/pull/114 since we are not yet ready to remove the `dist/` folder from the repository.
`pre-commit` at least will make this process a little less tedious and automated 😉 . It calls `prettier` and also checks if the `dist/` folder is out of date. In that case, we just need to call `git add dist/` to add the new bundled files compiled by `pre-commit`.
Closes #114

Set up pre-commit

---

.pre-commit-config.yaml
check-build-assets.sh

We need to check for the `git diff` because we want those changes to be stashed.
After some local testing, I think this is the _final_ version 😄

Update check build assets

---

web-test-runner.config.mjs

Preferred default export mode is not required anymore, and this plays
nicely with other TS libraries.
Refs #182

Alter the configuration around externals and default exports

---

CHANGELOG.rst

I found that 0.9.1 was duplicated and created confusions.

Changelog: fix inconsistencies

---

webpack.config.js

We are not using this anymore.
This was useful while I was developing the addons, but it's not required anymore.
I'm removing it here because it's also having conflicts with the latest version of Webpack that requires this config to be updated.

Development: remove webpack proxy

---

docs/conf.py

The theme should include this into the `html_context` automatically, but for some reason this is not working like that.

Docs: add environment variable

---

.github/workflows/ncu.yaml

Don't update `rollup/plugin-commonjs` for now until we figure it out how to solve the tests with the latest version.
Closes #425

ncu: reject `rollup/plugin-commonjs`

---

src/utils.js

It seems this is common enough in other doc tools,
I think we should probably include it in the default?
I hit this with markdoc, where `main` includes the sidebars and other non-primary content.

Add `article` to the FALLBACK_DOCTOOL list

---

docs/releasing.rst

Release: this step is not required anymore

---

public/_/readthedocs-addons.json

This was breaking my local setup

Fix invalid syntax in readthedocs-addons.json

---

src/search.js

Initially I implemented a custom event to achieve this, but in the end, simply using `click` event seemed like a much cleaner solution.
Closes #399

Fix storing recent search when using keyboard

---

src/linkpreviews.js
src/utils.js

Tell the EmbedAPI what's the selector for the main content of the page. This allows the backend to know exactly what content to return when the whole page has to be returned.
Requires https://github.com/readthedocs/readthedocs.org/pull/11812

Links preview: specify the `?selector=` attribute

---

public/customscript.js
src/filetreediff.js

- Don't break the custom script if the element is not found
- Don't break filetreediff if there are no files

Minor bugfixes

---

src/ethicalads.css
src/ethicalads.js
src/utils.js

Show how simple is to add a better ad positioning for a documentation tool that we know.
1. Find the CSS selector that allows to detect the framework
2. Find the CSS selector for the ad position
3. Add small CSS for styling if required
Related https://github.com/readthedocs/addons/pull/447

EthicalAd: better ad position for Docsify

---

src/notification.js
tests/notification.test.html

I think this is maybe a better default than https://github.com/readthedocs/readthedocs.org/pull/11874.
This should at least stop the "getting a notification when I hit the default version" issue. Though maybe it's better to default it to off, instead of this? I think we need to do _something_ to fix the current behavior because it's properly annoying (I hit the latest version warning like 3 times yesterday trying to do basic work, and it was never useful..)

Don't show the `latest` notification if it's the default version

---

src/doctools.css
src/flyout.css
src/flyout.js
src/index.js

This moves the inner CSS rules from inside the shadow DOM to the parent
DOM. This allows users to still set a `--readthedocs-font-size` and
similar variables.

Show example of setting attributes and variables at parent DOM

---

src/flyout.js

Initial POC to prove if this idea is possible and how we feel about it.
I put together an example of what I understand we want to build here 😅 . In this example, the theme author will make explicitly how they want to use `readthedocs-flyout` HTML tag:
```html
<readthedocs-flyout position="top-right"></readthedocs-flyout>
```
That will add the class `top-right` and show the flyout as follows:
However, the project author can change the `position` value from the dashboard if they prefer to override the theme's default value:
* Related #51
* Requires https://github.com/readthedocs/ext-theme/pull/554
* Requires https://github.com/readthedocs/readthedocs.org/pull/11891
* Example using https://test-builds.readthedocs.io/en/addons-theme-defaults/
* Closes #434

Flyout: use theme default for `position`

---

public/index.html
src/context.js
src/flyout.js

Additional elements shouldn't be needed in our structure. This is how we can use ContextRoot with `document.html` as the context root for providers/consumers of the config context.
Both the flyout and the notifications load for me with this change.

Use ContextRoot at document.html instead

---

src/search.css

Based on my feedback from #496
This is the results. I think it looks a lot better, more compacted and easy to quickly scan.
Closes #496
Closes #419

Search: small updates on look & feel

---

src/docdiff.js
src/filetreediff.css
src/filetreediff.js
src/index.js

This adds a v1 Visual Diff UI.
It does the following:
* Adds a UI element to track Docdiff state, and exposes filetreediff as a dropdown
* Updates the URL to track diff state
* Updates the UI element to show state based on events (eg. hotkeys)
* Shows the current file in the dropdown if it's open, otherwise a generic message
Fixes https://github.com/readthedocs/meta/issues/171
https://github.com/user-attachments/assets/768c7bbf-e8f2-4753-8d69-1ac718b52b69

Visual Diff UI v1

---

src/linkpreviews.js
src/utils.js

Check if from/to URL are different after removing `?readthedocs-diff=`
attribute because we don't want to trigger the even when the user enabled
docdiff in the current page.
Closes #506

Trigger the URL_CHANGED event only if from/to URL are different

---

src/filetreediff.js

This will help detecting changes inside `section`, `ul` and `ol`.
Example: https://writethedocs-www--2299.org.readthedocs.build/conf/index.html?readthedocs-diff=true

Visual diff: add extra CSS chunk selectors

---

src/ethicalads.js
src/filetreediff.js

We want to validate _first_ for the simplest condition and if that condition is met, we want to perform the other more expensive checks.
This avoid raising "Validation error on..." for every page when the version is not external, for example.

`isEnabled` order of check

---

src/ethicalads.js

This was causing the addon to break

EthicalAd: minor fix when checking `isEnabled`

---

src/linkpreviews.js
tests/__snapshots__/search.test.snap.js
tests/search.test.html

Keep a cache of all the API request calls done and re-use them when the same link is previewed again. It follows the same logic we use on docdiff.

Links preview: cache requests to API

---

src/search.css

Fixes https://github.com/readthedocs/addons/issues/420

Force black text for search input

---

src/readthedocs-config.js
tests/__snapshots__/search.test.snap.js
tests/hotkeys.test.html
tests/readthedocs-config.test.html
tests/search.test.html
tests/utils.test.html

Test: `readthedocs-addons-data-ready`

---

src/hotkeys.js

Avoid triggering hotkeys when the active element has `contentEditable=true`.
Closes #558

Hotkeys: support `contenteditable`

---

docs/index.rst

Typlog is archived and Shibuya is the new fancy version of it.

Docs: replace typlog by shibuya

---

tests/ethicalads.test.html

`fixture` expects the element to have a specific method:
https://open-wc.org/docs/testing/helpers/#timings
Since a regular `div` doesn't have that method, it fails.
I found this while upgrading the packages using `ncu`. It seems that newer versions are more strict -- which makes sense. Related #580

Tests: do not use `fixture` for simple elements

---

src/utils.js

I was using a "startswith" approach, but that didn't covered checking for these files on subpages where the `href` was more like `../_static/js/theme.js`.
I'm changing to a "contains" approach instead, which works better here.
As an example, a page like
https://docs.readthedocs.com/platform/latest/guides/best-practice/links.html was not being detected as `sphinx`.

Improve tools detection

---

src/defaults.css
src/filetreediff.css

Visual diff: use default CSS variables for Material for MkDocs

---

src/search.js

Read the addons API and enable/disable the filters by default based on that data. This is an initial and immediate simple solution for #22 without implementing all the features.
Basically, all projects that have subprojects will now have "Include subprojects" checked by default. In the future, we will allow users to enable/disable this per project.

Search: filters enabled by default

---

src/data-validation.js
tests/notification.test.html

When a project is private and version private the current build can be null. This was presenting as an exception in validation, especially for the notification addon.

Fix issue with null current build validation

---

src/ethicalads.js
tests/__snapshots__/ethicalads.test.snap.js
tests/ethicalads.test.html

This is a POC to show how we can use fixed footer ad on specific known themes. The logic is as follows:
- the theme has to be a known theme
- the image ad added to the navbar has to be below the fold
- show a fixed footer ad and we add some `padding-bottom` CSS style to the
content container (theme-specific selector) with the height of the fixed
footer ad (using fixed `47.2px` for now but it can be dynamically calculated)
The technique of adding the `padding-bottom` to a theme-specific element solves the problem highlighted in the previous approach done in https://github.com/readthedocs/addons/pull/447
[Peek 2025-07-07 12-59.webm](https://github.com/user-attachments/assets/62c455d5-3fbd-4e8c-b2b9-9e5f0987e502)
[Peek 2025-07-07 13-10.webm](https://github.com/user-attachments/assets/ec2cf1f1 …

EthicalAd: fixed footer placement for specific themes

---

public/_/readthedocs-addons.json
src/data-validation.js
src/linkpreviews.js
tests/linkpreviews.test.html
tests/linkpreviews.test.js

Requires:
* https://github.com/readthedocs/readthedocs.org/pull/12301
* https://github.com/readthedocs/ext-theme/pull/626
Closes #554

Link previews: use `selector` field from API

---

src/analytics.js
src/data-validation.js
tests/analytics.test.html

Required by https://github.com/readthedocs/readthedocs.org/issues/12307

Analytics: send `?status` to the backend

---

src/ethicalads.js

This is the logic we follow to show the fixed footer ad:
* We detect the doctool/theme using our common heuristic.
* The image nav bar ad is below the fold.
* Inject the fixed footer ad on a specific selector (if needed, eg. "body").
* Add `padding-bottom` to specific CSS selectors to not cover content.
Closes https://github.com/readthedocs/meta/issues/192

EthicalAd: add support for fixed footer ad in all the themes
