readthedocs/addons

README.md

Very basic for now, but we can expand as needed.

Basic documentation on how to start the local environment

---

CHANGELOG.rst
bumpver.toml
docs/releasing.rst

Define and document the release process.
Closes #105

Docs: release process

---

.pre-commit-config.yaml
.pre-commit-hooks.yaml

Run our own hook over CSS or JS or SVG.

pre-commit: we need types_or for this

---

webpack.config.js

We are adding this parameters in production, so it makes sense to have parity here as well.

Development: add `async` and `type`

---

docs/releasing.rst

Small update to mention env variables and link to the script.

Docs: mention environment variables

---

CHANGELOG.rst

I forgot to add these two in the release.

Docs: update changelog

---

docs/releasing.rst

Docs: add extra release step

---

public/_/readthedocs-addons.json

File Tree Diff: add small example in the homepage

---

.circleci/config.yml
.pre-commit-config.yaml
docs/testing.rst

We are doing this during the release.

Remove built assets up to date check

---

tests/utils.test.html

Test: add a few test for `DocumentationTool` helper

---

tests/utils.test.html

The PR that added these tests was merged _after_ we change the selector.

Test: fix failing test

---

README.md

Describes some of what was changed in #282, plus some notes on attributes

Add guidelines on attributes and CSS variables

---

src/flyout.js

I found that positioning wasn't working while building the AMIs. I opened this PR for a quick fix for now. It may not be the best pattern, but at least we won't deploy something broken at the first attempt. I'm happy to adapt/change it as wanted.

Flyout: quickfix before deploying

---

src/constants.js
src/ethicalads.js
src/utils.js

- Update `DocumentationTool` class to detect VitePress
- Add better ad positioning for this tool

Heuristic to detect VitePress

---

src/filetreediff.css
src/filetreediff.js

Use relative names instead of classes,
and use rems instead of px.

Update FTD CSS

---

src/filetreediff.js

Filetreediff: don't show "Show diff" when docdiff is disabled

---

tests/__snapshots__/filetreediff.test.snap.js
tests/filetreediff.test.html

 Filetreediff: small test suite 

---

src/utils.js

```
Uncaught TypeError: r.searchParams is undefined
e utils.js:235
```

SPA: fix `setupHistoryEvent` bug

---

src/filetreediff.css

This is just a test to see how it looks following the flyout look and feel.

File Tree Diff: style to match flyout

---

src/filetreediff.css

Small adjustment to not break on mobile.
[Peek 2025-02-11 11-53.webm](https://github.com/user-attachments/assets/5fa4e490-374c-457e-8f8c-53fa773556b7)

File tree diff: style for mobile

---

src/docdiff.js
tests/docdiff.test.html

Visual diff: check for `rootSelector` before making request API

---

src/flyout.js

[Peek 2025-06-23 17-24.webm](https://github.com/user-attachments/assets/ea46c485-b825-4b2d-b5bc-bce42bb910dd)
Closes #585

Render flyout properly when showing search modal

---

src/search.js

Search: link for results from other projects
